// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(fern_coreFFI)
import fern_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_fern_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_fern_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A thread-safe API facade for the Swift side.
 */
public protocol FernApiProtocol : AnyObject {
    
    func archiveArea(id: String) throws 
    
    func completeProject(id: String) throws 
    
    func completeTask(id: String) throws 
    
    func createArea(area: Area) throws 
    
    func createProject(project: Project) throws 
    
    func createTask(task: Task) throws 
    
    func getActiveAreas() throws  -> [Area]
    
    func getAnytimeProjects() throws  -> [Project]
    
    func getAnytimeTasks() throws  -> [Task]
    
    func getInboxTasks() throws  -> [Task]
    
    func getLogbookTasks() throws  -> [Task]
    
    func getSomedayTasks() throws  -> [Task]
    
    func getTodayTasks() throws  -> [Task]
    
    func getUpcomingTasks() throws  -> [Task]
    
    func trashTask(id: String) throws 
    
    func updateTask(task: Task) throws 
    
}

/**
 * A thread-safe API facade for the Swift side.
 */
open class FernApi:
    FernApiProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_fern_core_fn_clone_fernapi(self.pointer, $0) }
    }
    /**
     * Creates a new persistence instance at the given file path.
     */
public convenience init(path: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_constructor_fernapi_new(
        FfiConverterString.lower(path),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_fern_core_fn_free_fernapi(pointer, $0) }
    }

    
    /**
     * Creates a new in-memory instance for testing.
     */
public static func newInMemory()throws  -> FernApi {
    return try  FfiConverterTypeFernAPI.lift(try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_constructor_fernapi_new_in_memory($0
    )
})
}
    

    
open func archiveArea(id: String)throws  {try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_archive_area(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
}
}
    
open func completeProject(id: String)throws  {try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_complete_project(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
}
}
    
open func completeTask(id: String)throws  {try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_complete_task(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
}
}
    
open func createArea(area: Area)throws  {try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_create_area(self.uniffiClonePointer(),
        FfiConverterTypeArea.lower(area),$0
    )
}
}
    
open func createProject(project: Project)throws  {try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_create_project(self.uniffiClonePointer(),
        FfiConverterTypeProject.lower(project),$0
    )
}
}
    
open func createTask(task: Task)throws  {try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_create_task(self.uniffiClonePointer(),
        FfiConverterTypeTask.lower(task),$0
    )
}
}
    
open func getActiveAreas()throws  -> [Area] {
    return try  FfiConverterSequenceTypeArea.lift(try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_get_active_areas(self.uniffiClonePointer(),$0
    )
})
}
    
open func getAnytimeProjects()throws  -> [Project] {
    return try  FfiConverterSequenceTypeProject.lift(try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_get_anytime_projects(self.uniffiClonePointer(),$0
    )
})
}
    
open func getAnytimeTasks()throws  -> [Task] {
    return try  FfiConverterSequenceTypeTask.lift(try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_get_anytime_tasks(self.uniffiClonePointer(),$0
    )
})
}
    
open func getInboxTasks()throws  -> [Task] {
    return try  FfiConverterSequenceTypeTask.lift(try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_get_inbox_tasks(self.uniffiClonePointer(),$0
    )
})
}
    
open func getLogbookTasks()throws  -> [Task] {
    return try  FfiConverterSequenceTypeTask.lift(try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_get_logbook_tasks(self.uniffiClonePointer(),$0
    )
})
}
    
open func getSomedayTasks()throws  -> [Task] {
    return try  FfiConverterSequenceTypeTask.lift(try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_get_someday_tasks(self.uniffiClonePointer(),$0
    )
})
}
    
open func getTodayTasks()throws  -> [Task] {
    return try  FfiConverterSequenceTypeTask.lift(try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_get_today_tasks(self.uniffiClonePointer(),$0
    )
})
}
    
open func getUpcomingTasks()throws  -> [Task] {
    return try  FfiConverterSequenceTypeTask.lift(try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_get_upcoming_tasks(self.uniffiClonePointer(),$0
    )
})
}
    
open func trashTask(id: String)throws  {try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_trash_task(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
}
}
    
open func updateTask(task: Task)throws  {try rustCallWithError(FfiConverterTypeFernError.lift) {
    uniffi_fern_core_fn_method_fernapi_update_task(self.uniffiClonePointer(),
        FfiConverterTypeTask.lower(task),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFernAPI: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FernApi

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FernApi {
        return FernApi(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FernApi) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FernApi {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FernApi, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFernAPI_lift(_ pointer: UnsafeMutableRawPointer) throws -> FernApi {
    return try FfiConverterTypeFernAPI.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFernAPI_lower(_ value: FernApi) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFernAPI.lower(value)
}


/**
 * Top-level organisational container (e.g. "Work", "Personal").
 *
 * Areas have no status — they can only be active (visible) or archived
 * (hidden from the sidebar, but all data is preserved).
 */
public struct Area {
    public var id: String
    public var title: String
    public var notes: String
    /**
     * Archived areas are hidden but never deleted. All their projects and tasks
     * remain queryable and are preserved for history and future sync.
     */
    public var isArchived: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, title: String, notes: String, 
        /**
         * Archived areas are hidden but never deleted. All their projects and tasks
         * remain queryable and are preserved for history and future sync.
         */isArchived: Bool) {
        self.id = id
        self.title = title
        self.notes = notes
        self.isArchived = isArchived
    }
}



extension Area: Equatable, Hashable {
    public static func ==(lhs: Area, rhs: Area) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.notes != rhs.notes {
            return false
        }
        if lhs.isArchived != rhs.isArchived {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(title)
        hasher.combine(notes)
        hasher.combine(isArchived)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeArea: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Area {
        return
            try Area(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                notes: FfiConverterString.read(from: &buf), 
                isArchived: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Area, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.notes, into: &buf)
        FfiConverterBool.write(value.isArchived, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArea_lift(_ buf: RustBuffer) throws -> Area {
    return try FfiConverterTypeArea.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArea_lower(_ value: Area) -> RustBuffer {
    return FfiConverterTypeArea.lower(value)
}


/**
 * A goal-oriented collection of Tasks, optionally belonging to an Area.
 *
 * # Which view does a project appear in?
 *
 * | Condition                                          | View      |
 * |----------------------------------------------------|-----------|
 * | `status=Todo`, `is_trashed=false`, no date         | Anytime   |
 * | `status=Todo`, `is_trashed=false`, date=Someday    | Someday   |
 * | `status=Done\|Cancelled`, `is_trashed=false`       | Logbook   |
 * | `is_trashed=true`                                  | Trash     |
 */
public struct Project {
    public var id: String
    public var areaId: String?
    public var title: String
    public var notes: String
    /**
     * When to work on this project. `None` = Anytime, `Someday` = deferred.
     * Note: this is distinct from `deadline` (which is a hard due date).
     */
    public var scheduledDate: ScheduledDate?
    public var deadline: NaiveDate?
    /**
     * The actual completion state. Logbook/Trash are derived from this + `is_trashed`.
     */
    public var status: ProjectStatus
    /**
     * If true, the project is in the Trash. Independent of `status`:
     * a Done project can also be trashed (and vice-versa).
     */
    public var isTrashed: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, areaId: String?, title: String, notes: String, 
        /**
         * When to work on this project. `None` = Anytime, `Someday` = deferred.
         * Note: this is distinct from `deadline` (which is a hard due date).
         */scheduledDate: ScheduledDate?, deadline: NaiveDate?, 
        /**
         * The actual completion state. Logbook/Trash are derived from this + `is_trashed`.
         */status: ProjectStatus, 
        /**
         * If true, the project is in the Trash. Independent of `status`:
         * a Done project can also be trashed (and vice-versa).
         */isTrashed: Bool) {
        self.id = id
        self.areaId = areaId
        self.title = title
        self.notes = notes
        self.scheduledDate = scheduledDate
        self.deadline = deadline
        self.status = status
        self.isTrashed = isTrashed
    }
}



extension Project: Equatable, Hashable {
    public static func ==(lhs: Project, rhs: Project) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.areaId != rhs.areaId {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.notes != rhs.notes {
            return false
        }
        if lhs.scheduledDate != rhs.scheduledDate {
            return false
        }
        if lhs.deadline != rhs.deadline {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        if lhs.isTrashed != rhs.isTrashed {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(areaId)
        hasher.combine(title)
        hasher.combine(notes)
        hasher.combine(scheduledDate)
        hasher.combine(deadline)
        hasher.combine(status)
        hasher.combine(isTrashed)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProject: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Project {
        return
            try Project(
                id: FfiConverterString.read(from: &buf), 
                areaId: FfiConverterOptionString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                notes: FfiConverterString.read(from: &buf), 
                scheduledDate: FfiConverterOptionTypeScheduledDate.read(from: &buf), 
                deadline: FfiConverterOptionTypeNaiveDate.read(from: &buf), 
                status: FfiConverterTypeProjectStatus.read(from: &buf), 
                isTrashed: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Project, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.areaId, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.notes, into: &buf)
        FfiConverterOptionTypeScheduledDate.write(value.scheduledDate, into: &buf)
        FfiConverterOptionTypeNaiveDate.write(value.deadline, into: &buf)
        FfiConverterTypeProjectStatus.write(value.status, into: &buf)
        FfiConverterBool.write(value.isTrashed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProject_lift(_ buf: RustBuffer) throws -> Project {
    return try FfiConverterTypeProject.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProject_lower(_ value: Project) -> RustBuffer {
    return FfiConverterTypeProject.lower(value)
}


/**
 * The atomic unit of work.
 *
 * # Which view does a task appear in?
 *
 * | Condition                                                          | View     |
 * |--------------------------------------------------------------------|----------|
 * | `Todo`, no project, no area, no date, not trashed                 | Inbox    |
 * | `Todo`, `scheduled_date=On{today}`, not trashed                   | Today    |
 * | `Todo`, `scheduled_date=On{future}`, not trashed                  | Upcoming |
 * | `Todo`, `scheduled_date=None`, not trashed                        | Anytime  |
 * | `Todo`, `scheduled_date=Someday`, not trashed                     | Someday  |
 * | `Done` or `Cancelled`, not trashed                                | Logbook  |
 * | `is_trashed=true`                                                  | Trash    |
 *
 * A task completed while in the Inbox (no project, no area, no date) will
 * appear in the Logbook — correctly preserving its origin context.
 */
public struct Task {
    public var id: String
    public var projectId: String?
    public var areaId: String?
    public var title: String
    public var notes: String
    /**
     * When to work on this task. `None` means Anytime (or Inbox if also unorganised).
     * `Someday` means deferred indefinitely.
     */
    public var scheduledDate: ScheduledDate?
    public var deadline: NaiveDate?
    /**
     * Estimated duration in minutes.
     */
    public var estimatedTime: Int64?
    /**
     * Actual time spent in minutes.
     */
    public var spentTime: Int64?
    /**
     * The actual completion state.
     */
    public var status: TaskStatus
    /**
     * If true, the task is in the Trash. Independent of `status`.
     */
    public var isTrashed: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, projectId: String?, areaId: String?, title: String, notes: String, 
        /**
         * When to work on this task. `None` means Anytime (or Inbox if also unorganised).
         * `Someday` means deferred indefinitely.
         */scheduledDate: ScheduledDate?, deadline: NaiveDate?, 
        /**
         * Estimated duration in minutes.
         */estimatedTime: Int64?, 
        /**
         * Actual time spent in minutes.
         */spentTime: Int64?, 
        /**
         * The actual completion state.
         */status: TaskStatus, 
        /**
         * If true, the task is in the Trash. Independent of `status`.
         */isTrashed: Bool) {
        self.id = id
        self.projectId = projectId
        self.areaId = areaId
        self.title = title
        self.notes = notes
        self.scheduledDate = scheduledDate
        self.deadline = deadline
        self.estimatedTime = estimatedTime
        self.spentTime = spentTime
        self.status = status
        self.isTrashed = isTrashed
    }
}



extension Task: Equatable, Hashable {
    public static func ==(lhs: Task, rhs: Task) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.projectId != rhs.projectId {
            return false
        }
        if lhs.areaId != rhs.areaId {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.notes != rhs.notes {
            return false
        }
        if lhs.scheduledDate != rhs.scheduledDate {
            return false
        }
        if lhs.deadline != rhs.deadline {
            return false
        }
        if lhs.estimatedTime != rhs.estimatedTime {
            return false
        }
        if lhs.spentTime != rhs.spentTime {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        if lhs.isTrashed != rhs.isTrashed {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(projectId)
        hasher.combine(areaId)
        hasher.combine(title)
        hasher.combine(notes)
        hasher.combine(scheduledDate)
        hasher.combine(deadline)
        hasher.combine(estimatedTime)
        hasher.combine(spentTime)
        hasher.combine(status)
        hasher.combine(isTrashed)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTask: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Task {
        return
            try Task(
                id: FfiConverterString.read(from: &buf), 
                projectId: FfiConverterOptionString.read(from: &buf), 
                areaId: FfiConverterOptionString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                notes: FfiConverterString.read(from: &buf), 
                scheduledDate: FfiConverterOptionTypeScheduledDate.read(from: &buf), 
                deadline: FfiConverterOptionTypeNaiveDate.read(from: &buf), 
                estimatedTime: FfiConverterOptionInt64.read(from: &buf), 
                spentTime: FfiConverterOptionInt64.read(from: &buf), 
                status: FfiConverterTypeTaskStatus.read(from: &buf), 
                isTrashed: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Task, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.projectId, into: &buf)
        FfiConverterOptionString.write(value.areaId, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.notes, into: &buf)
        FfiConverterOptionTypeScheduledDate.write(value.scheduledDate, into: &buf)
        FfiConverterOptionTypeNaiveDate.write(value.deadline, into: &buf)
        FfiConverterOptionInt64.write(value.estimatedTime, into: &buf)
        FfiConverterOptionInt64.write(value.spentTime, into: &buf)
        FfiConverterTypeTaskStatus.write(value.status, into: &buf)
        FfiConverterBool.write(value.isTrashed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTask_lift(_ buf: RustBuffer) throws -> Task {
    return try FfiConverterTypeTask.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTask_lower(_ value: Task) -> RustBuffer {
    return FfiConverterTypeTask.lower(value)
}


/**
 * A custom error type that will be exposed to Swift as an Error enum.
 */
public enum FernError {

    
    
    case DatabaseError(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFernError: FfiConverterRustBuffer {
    typealias SwiftType = FernError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FernError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .DatabaseError(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FernError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .DatabaseError(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension FernError: Equatable, Hashable {}

extension FernError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Completion state of a Project.
 */

public enum ProjectStatus {
    
    case todo
    case done
    case cancelled
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProjectStatus: FfiConverterRustBuffer {
    typealias SwiftType = ProjectStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProjectStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .todo
        
        case 2: return .done
        
        case 3: return .cancelled
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ProjectStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .todo:
            writeInt(&buf, Int32(1))
        
        
        case .done:
            writeInt(&buf, Int32(2))
        
        
        case .cancelled:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProjectStatus_lift(_ buf: RustBuffer) throws -> ProjectStatus {
    return try FfiConverterTypeProjectStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProjectStatus_lower(_ value: ProjectStatus) -> RustBuffer {
    return FfiConverterTypeProjectStatus.lower(value)
}



extension ProjectStatus: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * When an item is scheduled to be worked on.
 *
 * `None` (absence of this field) means "no date" → Anytime or Inbox.
 * `Someday` means "deferred, no concrete date" → Someday view.
 * `On { date, time }` means "scheduled for this day, optionally at this time".
 */

public enum ScheduledDate {
    
    /**
     * Deferred indefinitely. Item appears in the Someday view.
     */
    case someday
    /**
     * Scheduled for a specific day, with an optional notification time.
     */
    case on(date: NaiveDate, 
        /**
         * If set, a local notification will fire at this time on `date`.
         */time: NaiveTime?
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScheduledDate: FfiConverterRustBuffer {
    typealias SwiftType = ScheduledDate

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScheduledDate {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .someday
        
        case 2: return .on(date: try FfiConverterTypeNaiveDate.read(from: &buf), time: try FfiConverterOptionTypeNaiveTime.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ScheduledDate, into buf: inout [UInt8]) {
        switch value {
        
        
        case .someday:
            writeInt(&buf, Int32(1))
        
        
        case let .on(date,time):
            writeInt(&buf, Int32(2))
            FfiConverterTypeNaiveDate.write(date, into: &buf)
            FfiConverterOptionTypeNaiveTime.write(time, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScheduledDate_lift(_ buf: RustBuffer) throws -> ScheduledDate {
    return try FfiConverterTypeScheduledDate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScheduledDate_lower(_ value: ScheduledDate) -> RustBuffer {
    return FfiConverterTypeScheduledDate.lower(value)
}



extension ScheduledDate: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Completion state of a Task. The view a task appears in is determined by
 * its other fields (`scheduled_date`, `project_id`, `area_id`, `is_trashed`).
 */

public enum TaskStatus {
    
    case todo
    case done
    case cancelled
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTaskStatus: FfiConverterRustBuffer {
    typealias SwiftType = TaskStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TaskStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .todo
        
        case 2: return .done
        
        case 3: return .cancelled
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TaskStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .todo:
            writeInt(&buf, Int32(1))
        
        
        case .done:
            writeInt(&buf, Int32(2))
        
        
        case .cancelled:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskStatus_lift(_ buf: RustBuffer) throws -> TaskStatus {
    return try FfiConverterTypeTaskStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskStatus_lower(_ value: TaskStatus) -> RustBuffer {
    return FfiConverterTypeTaskStatus.lower(value)
}



extension TaskStatus: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeScheduledDate: FfiConverterRustBuffer {
    typealias SwiftType = ScheduledDate?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeScheduledDate.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeScheduledDate.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeNaiveDate: FfiConverterRustBuffer {
    typealias SwiftType = NaiveDate?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeNaiveDate.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeNaiveDate.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeNaiveTime: FfiConverterRustBuffer {
    typealias SwiftType = NaiveTime?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeNaiveTime.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeNaiveTime.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeArea: FfiConverterRustBuffer {
    typealias SwiftType = [Area]

    public static func write(_ value: [Area], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeArea.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Area] {
        let len: Int32 = try readInt(&buf)
        var seq = [Area]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeArea.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeProject: FfiConverterRustBuffer {
    typealias SwiftType = [Project]

    public static func write(_ value: [Project], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeProject.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Project] {
        let len: Int32 = try readInt(&buf)
        var seq = [Project]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeProject.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTask: FfiConverterRustBuffer {
    typealias SwiftType = [Task]

    public static func write(_ value: [Task], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTask.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Task] {
        let len: Int32 = try readInt(&buf)
        var seq = [Task]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTask.read(from: &buf))
        }
        return seq
    }
}


/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias NaiveDate = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNaiveDate: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NaiveDate {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: NaiveDate, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> NaiveDate {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: NaiveDate) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNaiveDate_lift(_ value: RustBuffer) throws -> NaiveDate {
    return try FfiConverterTypeNaiveDate.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNaiveDate_lower(_ value: NaiveDate) -> RustBuffer {
    return FfiConverterTypeNaiveDate.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias NaiveTime = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNaiveTime: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NaiveTime {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: NaiveTime, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> NaiveTime {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: NaiveTime) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNaiveTime_lift(_ value: RustBuffer) throws -> NaiveTime {
    return try FfiConverterTypeNaiveTime.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNaiveTime_lower(_ value: NaiveTime) -> RustBuffer {
    return FfiConverterTypeNaiveTime.lower(value)
}


private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_fern_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_archive_area() != 62408) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_complete_project() != 35945) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_complete_task() != 44753) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_create_area() != 43843) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_create_project() != 35976) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_create_task() != 31908) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_get_active_areas() != 15278) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_get_anytime_projects() != 48995) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_get_anytime_tasks() != 16507) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_get_inbox_tasks() != 6597) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_get_logbook_tasks() != 45990) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_get_someday_tasks() != 53033) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_get_today_tasks() != 42541) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_get_upcoming_tasks() != 62382) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_trash_task() != 30136) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_method_fernapi_update_task() != 53784) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_constructor_fernapi_new() != 31956) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fern_core_checksum_constructor_fernapi_new_in_memory() != 6373) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all